-- Suppression des données des tables
	DELETE FROM CLIENT;
	DELETE FROM CONTRAT;
	DELETE FROM VEHICULE;
	DELETE FROM ACCIDENT;
	DELETE FROM IMPLICATION;

-- Suppression des contraintes
	-- Table CLIENT
	ALTER TABLE CLIENT 		DROP PRIMARY KEY;
	
	-- Table CONTRAT
	ALTER TABLE CONTRAT 	DROP PRIMARY KEY;
	ALTER TABLE CONTRAT 	DROP FOREIGN KEY CTR_FK;
	
	-- Table VEHICULE
	ALTER TABLE VEHICULE 	DROP PRIMARY KEY;
	ALTER TABLE VEHICULE 	DROP FOREIGN KEY VEH_CTRFK;
	ALTER TABLE VEHICULE 	DROP FOREIGN KEY VEH_CLIFK;
	
	-- Table ACCIDENT
	ALTER TABLE ACCIDENT 	DROP PRIMARY KEY;
	
	-- Table IMPLICATION
	ALTER TABLE IMPLICATION	DROP PRIMARY KEY;
	ALTER TABLE IMPLICATION	DROP FOREIGN KEY IMP_VEHFK;
	ALTER TABLE IMPLICATION	DROP FOREIGN KEY IMP_ACCFK;
	
-- Suppression des index
	-- Table CLIENT
	ALTER TABLE CLIENT 		DROP INDEX XCLI_NOM;
	ALTER TABLE CLIENT 		DROP INDEX XCLI_NUMCTR;
	
	-- Table CONTRAT
	ALTER TABLE CONTRAT 	DROP INDEX XCTR_NUMCTR;
	ALTER TABLE CONTRAT 	DROP INDEX XCTR_SIGNATAIRE;
	
	-- Table VEHICULE
	ALTER TABLE VEHICULE 	DROP INDEX XVEH_NUMCLIENT;
	ALTER TABLE VEHICULE 	DROP INDEX XVEH_NUMCTR;
	ALTER TABLE VEHICULE 	DROP INDEX XVEH_NUMVEH;
	ALTER TABLE VEHICULE 	DROP INDEX XVEH_SIGNATAIRE;
	
	-- Table ACCIDENT
	ALTER TABLE ACCIDENT 	DROP INDEX XACC_DATE;
	ALTER TABLE ACCIDENT 	DROP INDEX XACC_NUMACC;
	
	-- Table IMPLICATION
	ALTER TABLE IMPLICATION	DROP INDEX XIMP_NUMVEH;
	ALTER TABLE IMPLICATION	DROP INDEX XIMP_NUMACC;
	
-- Suppression des tables
	DROP TABLE CLIENT;
	DROP TABLE CONTRAT;
	DROP TABLE VEHICULE;
	DROP TABLE ACCIDENT;
	DROP TABLE IMPLICATION;